### ISSUE TITLE
bn3 save editor view

### ISSUE THREAD

**Issue by bigfarts** [tangobattle/tango-launcher#34]
things to do:
- [x] folder support
  - [x] find where the folder info is stored in EWRAM
  - [x] add chip data and icons
  - [x] expose chip info via getFolderEditor
- [x] navicust support
  - [x] get navicust cata
  - [x] find where navicust data is stored in EWRAM
  - [x] expose navicust info via getNavicustEditor
- [x] style support
  - [x] find where style data is stored in EWRAM
  - [x] make a UI for this

**Comment by im-deepfriedwater** [comment]
eager to chip into one of the save editors next month when I get some free time, are there any documentation that might be helpful for getting acquainted with a save format like this? or should I just trial and error and figure out how the other ones are implemented?

**Comment by im-deepfriedwater** [comment]
awesome, that's helpful advice for getting started! looking forward to helping out as my schedule frees up!

**Comment by im-deepfriedwater** [comment]
op good thing I checked my email before I touched this task lol
